version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - Sv443
  ignore:
  - dependency-name: dependency-cruiser
    versions:
    - "> 9.23.2, < 10"
  - dependency-name: eslint
    versions:
    - "> 7.17.0, < 8"
  - dependency-name: eslint
    versions:
    - "> 7.3.0, < 7.4"
  - dependency-name: farmhash
    versions:
    - "> 3.1.0, < 4"
  - dependency-name: fuse.js
    versions:
    - "> 6.4.1, < 6.5"
  - dependency-name: madge
    versions:
    - "> 3.9.0, < 3.10"
  - dependency-name: madge
    versions:
    - "> 4.0.1, < 5"
  - dependency-name: rate-limiter-flexible
    versions:
    - "> 2.1.10, < 2.2"
  - dependency-name: snyk
    versions:
    - "> 1.369.2, < 1.370"
  - dependency-name: snyk
    versions:
    - "> 1.511.0, < 2"
  - dependency-name: table
    versions:
    - "> 6.0.1, < 6.1"
  - dependency-name: table
    versions:
    - "> 6.0.1, < 7"
  - dependency-name: dependency-cruiser
    versions:
    - 9.23.2
  - dependency-name: lodash
    versions:
    - 4.17.21
