--- 
blank_issues_enabled: true
contact_links:
  -
    name: "Documentation"
    about: "Please read the API documentation before opening a new issue"
    url: "https://jokeapi.dev/"
  -
    name: "Discussions"
    about: "If there's a specific topic you want to talk about, please open a new thread on the discussion board"
    url: "https://github.com/Sv443/JokeAPI/discussions"
  -
    name: "Chat"
    about: "If you want to chat with the JokeAPI community, you can join my Discord server"
    url: "https://dc.sv443.net"
