---
blank_issues_enabled: true
contact_links:
  -
    name: "Documentation"
    about: "Please read the documentation before opening a new issue"
    url: "https://v3.jokeapi.dev/"
  -
    name: "Discussions"
    about: "If there's some topic you want to talk about, please open a new thread on the JokeAPI discussion board"
    url: "https://github.com/Sv443-Network/JokeAPI/discussions"
  -
    name: "Chat"
    about: "If you want to chat with the JokeAPI community, you can join my Discord server"
    url: "https://sv443.net/discord"
