name: JokeAPI CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        dir
        npm ci
        dir
        npm run lint --if-present
        npm run validate-jokes --if-present
        npm run reassign-ids --if-present
      env:
        CI: "true"
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        COMMIT_SHA: ${{ GITHUB_SHA }}
      uses: Ilshidur/action-discord@master
      with:
        args: '☑️ JokeAPI CI run was successful.\nSee https://github.com/Sv443/JokeAPI/commit/${{ COMMIT_SHA }}/checks'
