name: "Validate"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ] # runs on every push


jobs:
  validate:
    name: Build and Validate
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1 # checkout latest commit
    - name: Use Node.js ${{ matrix.node-version }} # set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm v8 # it's just better
      run: npm i -g npm@8
    - name: Install dependencies & link binary # install dependencies from the lockfile, then link the CLI binary to register the 'jokeapi' (alias 'japi') commands
      run: |
        npm ci
        npm run link
      env:
        CI: "true"
    - name: Validate joke files # validates the joke files
      run: japi vj
    - name: Validate joke IDs # makes sure all jokes have the correct ID
      run: japi vi
    - name: Display API info # uses info command to print some info about JokeAPI
      run: japi info
      env:
        NODE_ENV: prod # disable debug messages (default enabled on stage)
